In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('DummyDataset.csv')
x=dataset.iloc[:,6:8].values
y=dataset.iloc[:,8].values

In [3]:
print(x)

[[  2 382]
 [  1 299]
 [  4  82]
 ...
 [  1 284]
 [  5 229]
 [  3 220]]


In [4]:
print(y)

[10  7  4 ... 12  1 16]


In [5]:
# from sklearn import preprocessing
# # le = preprocessing.LabelEncoder()
# dataset["IPC Section"]=le.fit_transform(dataset["IPC Section"])
# # le.inverse_transform(dataset["IPC Section"])
# print(dataset["IPC Section"])

In [6]:
# x=dataset.iloc[:,5:8].values

In [7]:
print(x)

[[  2 382]
 [  1 299]
 [  4  82]
 ...
 [  1 284]
 [  5 229]
 [  3 220]]


In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [9]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(x, y)

DecisionTreeRegressor(random_state=0)

In [10]:
y_pred = regressor.predict(x_test)

In [11]:
import sklearn.metrics as sm
print("R2 score =", round(sm.r2_score(y_test, y_pred), 2))

R2 score = 0.28


In [12]:
print(regressor.predict([[2,382]]))

[8.]
